version: '2'
services:
  python:
    build:
      context: .
      args:
        - HTTP_PROXY
        - http_proxy
        - HTTPS_PROXY
        - https_proxy
    depends_on:
      - etcd
    links:
      - etcd
    environment:
      - ETCD_ENDPOINT=http://etcd:2379
  etcd:
    ports:
      - "2379:2379"
    image: quay.io/coreos/etcd
    command: etcd --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://127.0.0.1:2379
